### ISSUE TITLE
Make client prompt for user's input length constraint handler

### ISSUE THREAD

**Issue by momozor** [momozor/quaremain-vue-client#12]
Handles https://github.com/momozor/quaremain/issues/10 for the UI prompt. 

## Constraints
- name: 5 min characters, 250 max characters
- description (if exist): 20 min characters, 1500 max characters
- stockAmount(amount in general): 1 min, 999999999 max
- costPerPackage: 1 (or 1.xx) min, 9999999999999 max (or 9999999999999.xx)
- caloriesPerPackage(food): 1 min, 9999999999999 max
- millilitrePerPackage(water): 1 min, 9999999999999 max

**Comment by momozor** [comment]
Apparently, the client will prompt a constraint error if the user input is invalid according to the constraint validation.

However, it seems it requires the user to input something to make the error popup actually shows. 

Tested on water creation.

**Comment by j0sephh123** [comment]
Hmm, from the client code -> there is no validation at all

1. `CreateStock.vue` - just gather the input fields
2. `dispatch('submit', this.fields)` -> very stupid name 
3. just assign in `StockModel.js`

There are good validation classes [here](https://bootswatch.com/minty/), so I intend to use them.

**Comment by j0sephh123** [comment]
About the cost limit, should we use something more.. possible ? :D

**Comment by momozor** [comment]
> About the numbers limit, should we use something more.. possible ? :D

What do you mean exactly?

**Comment by j0sephh123** [comment]
> > About the numbers limit, should we use something more.. possible ? :D
> 
> What do you mean to be exact?

Just a smaller max number. 
Doesn't JS have problems with calculating big numbers? (not completely sure about that)

**Comment by momozor** [comment]
> > > About the numbers limit, should we use something more.. possible ? :D
> > 
> > 
> > What do you mean to be exact?
> 
> Just a smaller max number.
> Doesn't JS have problems with calculating big numbers? (not completely sure about that)

Sure, what do you think the max number should be? (Also, FYI there is https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt if it is needed).

**Comment by j0sephh123** [comment]
Actually, I've no idea. Can't give a good suggestion here. 
For now we can leave them as they are and I'll try to add helper texts and validation in the form inputs.

**Comment by momozor** [comment]
> Actually, I've no idea. Can't give a good suggestion here.
> For now we can leave them as they are and I'll try to add helper texts and validation in the form inputs.

Alright! :D
